### ISSUE TITLE
对android不支持问题

### ISSUE THREAD

**Issue by jiaoyigui** [KenHky/react-native-modal-date-picker#3]
用react-native相对android的支持不了
一个是react-native-picker-android引入问题
一个是渲染不出日期条目

**Comment by chenqiang1121** [comment]
bug还挺多的，如果没有初始日期会出错，android下项目直接无法运行， 报错 can not find variable:PickerAndroid

**Comment by KenHky** [comment]
1.02 版本修复了这些问题，我关闭这个 issue 了
