### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by AbelHuai** [KenHky/react-native-modal-date-picker#4]
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/jrwm/react-native-picker-android.git
npm ERR! 
npm ERR! Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Abel/.npm/_logs/2017-09-19T01_53_02_533Z-debug.log

**Comment by KenHky** [comment]
fixed in v1.0.3
